version: '3.0'
services:
  home-library-service:
    env_file:
      - .env
    image: home-library-service
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
    restart: always
    depends_on:
      - db
    volumes:
        - .:${WORK_DIR}
        - ${WORK_DIR}/node_modules
    networks:
      - hl-network
  db:
    env_file:
      - .env
    build: ${PATH_TO_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - PATH_TO_DATABASE=${PATH_TO_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGDATA=${DATABASE_DATA}
    volumes:
      - ${DATABASE_VOLUMES}:${DATABASE_DATA}
    networks:
        - hl-network
networks:
  hl-network:
    driver: bridge
